#Dictionnaries to link parameter codes (from Transparency ENTSOE API) with actual definitions
dic_documentType = {
    "A09": "Finalized schedule",
    "A11": "Aggregated energy data report",
    "A15": "Acquiring system operator reserve schedule",
    "A24": "Bid document",
    "A25": "Allocation result document",
    "A26": "Capacity document",
    "A31": "Agreed capacity",
    "A37": "Reserve bid document",
    "A38": "Reserve allocation result document",
    "A44": "Price Document",
    "A61": "Estimated Net Transfer Capacity",
    "A63": "Redispatch notice",
    "A65": "System total load",
    "A68": "Installed generation per type",
    "A69": "Wind and solar forecast",
    "A70": "Load forecast margin",
    "A71": "Generation forecast",
    "A72": "Reservoir filling information",
    "A73": "Actual generation",
    "A74": "Wind and solar generation",
    "A75": "Actual generation per type",
    "A76": "Load unavailability",
    "A77": "Production unavailability",
    "A78": "Transmission unavailability",
    "A79": "Offshore grid infrastructure unavailability",
    "A80": "Generation unavailability",
    "A81": "Contracted reserves",
    "A82": "Accepted offers",
    "A83": "Activated balancing quantities",
    "A84": "Activated balancing prices",
    "A85": "Imbalance prices",
    "A86": "Imbalance volume",
    "A87": "Financial situation",
    "A88": "Cross border balancing",
    "A89": "Contracted reserve prices",
    "A90": "Interconnection network expansion",
    "A91": "Counter trade notice",
    "A92": "Congestion costs",
    "A93": "DC link capacity",
    "A94": "Non EU allocations",
    "A95": "Configuration document",
    "B11": "Flow-based allocations",
    "B17": "Aggregated netted external TSO schedule document",
    "B45": "Bid Availability Document"
}

dic_processType = {
    "A01": "Day ahead",
    "A02": "Intra day incremental",
    "A16": "Realised",
    "A18": "Intraday total",
    "A31": "Week ahead",
    "A32": "Month ahead",
    "A33": "Year ahead",
    "A39": "Synchronisation process",
    "A40": "Intraday process",
    "A46": "Replacement reserve",
    "A47": "Manual frequency restoration reserve",
    "A51": "Automatic frequency restoration reserve",
    "A52": "Frequency containment reserve",
    "A56": "Frequency restoration reserve",
    "A60": "Scheduled activation mFRR",
    "A61": "Direct activation mFRR",
    "A67": "Central Selection aFRR",
    "A68": "Local Selection aFRR"
}

dic_businessType = {
    "A01": "Production",
    "A04": "Consumption",
    "A19": "Balance energy deviation",
    "A25": "General Capacity Information",
    "A29": "Already allocated capacity (AAC)",
    "A37": "Installed generation",
    "A43": "Requested capacity (without price)",
    "A46": "System Operator re-dispatching",
    "A53": "Planned maintenance",
    "A54": "Unplanned outage",
    "A60": "Minimum possible",
    "A61": "Maximum possible",
    "A85": "Internal re-dispatch",
    "A91": "Positive forecast margin",
    "A92": "Negative forecast margin",
    "A93": "Wind generation",
    "A94": "Solar generation",
    "A95": "Frequency containment reserve",
    "A96": "Automatic frequency restoration reserve",
    "A97": "Manual frequency restoration reserve",
    "A98": "Replacement reserve",
    "B01": "Interconnector network evolution",
    "B02": "Interconnector network dismantling",
    "B03": "Counter trade",
    "B04": "Congestion costs",
    "B05": "Capacity allocated (including price)",
    "B07": "Auction revenue",
    "B08": "Total nominated capacity",
    "B09": "Net position",
    "B10": "Congestion income",
    "B11": "Production unit",
    "B33": "Area Control Error",
    "B74": "Offer",
    "B75": "Need",
    "B95": "Procured capacity",
    "C22": "Shared Balancing Reserve Capacity",
    "C23": "Share of reserve capacity",
    "C24": "Actual reserve capacity",
    "C76": "Forecasted capacity",
    "C77": "Min",
    "C78": "Average",
    "C79": "Max"
}

dic_MktPSRType = {
    "A03": "Mixed",
    "A04": "Generation",
    "A05": "Load",
    "B01": "Biomass",
    "B02": "Fossil Brown coal/Lignite",
    "B03": "Fossil Coal-derived gas",
    "B04": "Fossil Gas",
    "B05": "Fossil Hard coal",
    "B06": "Fossil Oil",
    "B07": "Fossil Oil shale",
    "B08": "Fossil Peat",
    "B09": "Geothermal",
    "B10": "Hydro Pumped Storage",
    "B11": "Hydro Run-of-river and poundage",
    "B12": "Hydro Water Reservoir",
    "B13": "Marine",
    "B14": "Nuclear",
    "B15": "Other renewable",
    "B16": "Solar",
    "B17": "Waste",
    "B18": "Wind Offshore",
    "B19": "Wind Onshore",
    "B20": "Other",
    "B21": "AC Link",
    "B22": "DC Link",
    "B23": "Substation",
    "B24": "Transformer",
    "B25": "Energy storage"
}

all_dics = {"documentType": dic_documentType,
            "processType": dic_processType,
            "businessType": dic_businessType,
            "MktPSRType": dic_MktPSRType}

